# Generated by Django 3.2.8 on 2021-11-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_remove_juego_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='imagen',
        ),
    ]
